packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  '@nestjs/core': true
  '@scarf/scarf': true

minimumReleaseAgeExclude:
  - '@types/node@26.0.0'
